# Generated by Django 3.0.6 on 2020-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0013_auto_20200922_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hist_voo2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2015_9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2016_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2016_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hist_voo2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=4)),
                ('numVoo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Realizada', 'Viagem Realizada'), ('Cancelada', 'Viagem Cancelada')], default='Sem conhecimento', max_length=10)),
                ('tipoLinha', models.CharField(default='Sem Dados', max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fktipoprod',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='venda_produto',
            name='fkproduto',
        ),
        migrations.RemoveField(
            model_name='venda_produto',
            name='fkvenda',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='TipoCargo',
        ),
        migrations.DeleteModel(
            name='TipoProduto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.DeleteModel(
            name='Venda_Produto',
        ),
    ]
