# Generated by Django 3.0.6 on 2020-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpad', '0018_auto_20201006_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_voo2015',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_10',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_11',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_12',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_2',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_3',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_4',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_5',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_6',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_7',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_8',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2015_9',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2016',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2016_2',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2016_3',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2017',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2018',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='hist_voo2019',
            name='numVoo',
            field=models.PositiveIntegerField(max_length=6, null=True),
        ),
    ]
